name: Create Release and Upload Asset

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Retrieve version
        id: get_version
        run: |
          if [ ! -f VERSION ]; then
            echo "VERSION file not found!"
            exit 1
          fi
          VERSION=$(jq -r '.version' VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Clean up previous builds
        run: rm -rf AutoEquip.zip package

      - name: Package files
        run: |
          mkdir -p package/AutoEquip
          cp -r LibACE package/AutoEquip/
          cp -r Locales package/AutoEquip/
          cp -r Sources package/AutoEquip/
          cp -r Utils package/AutoEquip/
          cp LICENSE package/AutoEquip/
          cp README.md package/AutoEquip/
          cp VERSION package/AutoEquip/
          cp AutoEquip.toc package/AutoEquip/
          cd package
          zip -r ../AutoEquip.zip AutoEquip

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token

      - name: Create Release
        run: |
          tag_name="v${{ env.VERSION }}"
          release_name="AutoEquip Release $tag_name"
          release_body="Release description"
          gh release create $tag_name AutoEquip.zip --title "$release_name" --notes "$release_body"
